# Generated by Django 4.1 on 2022-10-26 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_overview', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Donasi',
        ),
    ]
