# Generated by Django 4.1 on 2022-10-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_overview', '0005_alter_donasi_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='donasi',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
