# Generated by Django 4.1 on 2022-10-28 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_overview', '0007_donasi_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donasi',
            name='deadline',
        ),
    ]
