# Generated by Django 4.1 on 2022-10-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_overview', '0008_remove_donasi_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='donasi',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
