# Generated by Django 4.1 on 2022-10-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengguna',
            name='username',
            field=models.CharField(default=None, max_length=30, unique=True),
        ),
    ]
