# Generated by Django 4.1 on 2022-11-01 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_remove_article_body_article_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='body',
        ),
    ]
