# Generated by Django 4.1 on 2022-10-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harapan_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='harapandonatur',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='harapandonatur',
            old_name='description',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='harapandonatur',
            name='title',
        ),
        migrations.AddField(
            model_name='harapandonatur',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
