# Generated by Django 4.1 on 2022-10-27 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harapan_page', '0002_rename_date_harapandonatur_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harapandonatur',
            name='harapan_image',
        ),
    ]
