# Generated by Django 4.1 on 2022-10-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harapan_page', '0004_harapandonatur_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='harapandonatur',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
