# Generated by Django 4.1 on 2022-10-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harapan_page', '0006_remove_harapandonatur_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='harapandonatur',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
