# Generated by Django 4.1 on 2022-10-28 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harapan_page', '0007_harapandonatur_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harapandonatur',
            name='likes',
        ),
    ]
