# Generated by Django 4.1 on 2022-11-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harapan_page', '0008_remove_harapandonatur_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harapandonatur',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
